FROM python:3.11.2

WORKDIR /usr/src/pyapp

COPY data_wathering.py .
COPY requirements.txt .
COPY models.py .
COPY config.json .

RUN pip install -r requirements.txt

CMD [ "python", "data_wathering.py" ]