name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]


jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Create .env file
      run: | # have to define secrets --> OK
        echo '${{ secrets.ENV_FILE }}' > .env 

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # this token gonna recreate automaticly of each workflow start

    - name: Build and push first Image
      uses: docker/build-push-action@v5
      with:
        context: ./watering_system
        push: true
        tags: |
          ghcr.io/gluecka/py-trigger:latest
          ghcr.io/gluecka/py-trigger:${{ github.sha }}
    
    - name: Deploy to Raspberry via SSH (Docker compose)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e

          cd watering_system
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          git pull origin master

          docker rmi -f ghcr.io/gluecka/py-trigger:latest

          docker compose -f docker-compose.service.yml --profile summer up -d
