name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]


jobs:

  filter-job:
    runs-on: ubuntu-latest

    outputs:
      trigger: ${{ steps.changes.outputs.trigger }}
      wathering: ${{ steps.changes.outputs.wathering }}
      weather: ${{ steps.changes.outputs.weather }}

    steps:
    - uses: actions/checkout@v4

    - name: Check changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          trigger:
            - 'trigger.py'
          wathering:
            - 'data_wathering.py'
          weather:
            - 'data_weather.py'

  build-and-deploy:
    needs: filter-job
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    # - name: Create .env file
    #   run: | # have to define secrets --> OK
    #     echo '${{ secrets.ENV_FILE }}' > .env 

    - name: Checkout repository
      uses: actions/checkout@v4

    
    # Multiarchitecture Support
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generater Timestamp
      id: time
      run: echo 'timestamp = $(date +'%Y%m%d-%H%M%S')' >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # this token gonna recreate automaticly of each workflow start

    - name: Build and push trigger Image
      if: ${{ needs.filter-job.outputs.trigger == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.trigger
        push: true
        platforms: linux/amd64, linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/py-trigger:latest
          ghcr.io/${{ github.repository_owner }}/py-trigger:${{ steps.time.outputs.timestamp }}

    - name: Build and push wathering Image
      if: ${{ needs.filter-job.outputs.wathering == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.data_wathering
        push: true
        platforms: linux/amd64, linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/py-wathering:latest
          ghcr.io/${{ github.repository_owner }}/py-wathering:${{ steps.time.outputs.timestamp }}

    - name: Build and push weather Image
      if: ${{ needs.filter-job.outputs.weather == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.data_weather
        push: true
        platforms: linux/amd64, linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/py-weather:latest
          ghcr.io/${{ github.repository_owner }}/py-weather:${{ steps.time.outputs.timestamp }}


  connetion-and-deploy-to-raspberry-via-ssh:

    permissions:
      contents: read
      packages: write
    
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # this token gonna recreate automaticly of each workflow start

    - name: Deploy to Raspberry (Docker compose)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e

          cd watering_system
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          git pull origin master

          docker rmi -f ghcr.io/${{ github.repository_owner }}/py-trigger:latest
          docker rmi -f ghcr.io/${{ github.repository_owner }}/py-wathering:latest
          docker rmi -f ghcr.io/${{ github.repository_owner }}/py-weather:latest

          docker compose -f docker-compose.service.yml --profile summer up -d
          docker system prune -f

    - name: Cleanup old Docker Images
      uses: actions/delete-package-versions@v5
      with:
        package-name: |
          py-trigger
          py-wathering
          py-weather
        package-type: container
        min-versions-to-keep: 5
